map_compressor:
  ros__parameters:
    debug: false
    # Transformation from the coordinate system of lidar to origin
    transform:
      translation:
        x: 0.0
        y: 0.0
        z: -0.55
      quaternion:
        x: 0.0
        y: 1.0
        z: 0.0
        w: 1.0
    grid:
      resolution: 0.1
      width: 100
